//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Cod_Venta { get; set; }
        public string Cod_Cliente { get; set; }
        public System.DateTime Fecha_Venta { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Veta_Estado Veta_Estado { get; set; }
    }
}
