//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veta_Estado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veta_Estado()
        {
            this.Envio = new HashSet<Envio>();
        }
    
        public int Cod_Venta_Estado { get; set; }
        public int Cod_Estado { get; set; }
        public System.DateTime Fecha_Vecha { get; set; }
        public string Cod_Pedido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envio> Envio { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pedido_de_Venta Pedido_de_Venta { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
