//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_de_Compras
    {
        public string Cod_Compra { get; set; }
        public string Cod_Proveedor { get; set; }
        public string Cod_Producto { get; set; }
        public int Precio_Compra { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
