//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public string Cod_Envio { get; set; }
        public int Cod_Venta_Estado { get; set; }
        public string Cod_Pedido { get; set; }
        public string Cod_Sucursal { get; set; }
        public string Cod_Repartidores { get; set; }
    
        public virtual Pedido_de_Venta Pedido_de_Venta { get; set; }
        public virtual Repartidores Repartidores { get; set; }
        public virtual Sucursales Sucursales { get; set; }
        public virtual Venta_Estado Venta_Estado { get; set; }
    }
}
