//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Detalle_de_Compras = new HashSet<Detalle_de_Compras>();
            this.Pedido_de_Venta = new HashSet<Pedido_de_Venta>();
            this.Producto_Sucursal = new HashSet<Producto_Sucursal>();
        }
    
        public string Cod_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public string Cod_Marca { get; set; }
        public string Informacion { get; set; }
        public int Precio_Venta { get; set; }
        public string Oferta { get; set; }
        public string Cod_SubCategoria { get; set; }
        public string URLVideo { get; set; }
        public string stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_de_Compras> Detalle_de_Compras { get; set; }
        public virtual Marcas Marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_de_Venta> Pedido_de_Venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Sucursal> Producto_Sucursal { get; set; }
        public virtual SubCategoria SubCategoria { get; set; }
    }
}
