//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Sucursal
    {
        public string Cod_Producto { get; set; }
        public string Cod_Sucursal { get; set; }
        public int Stock { get; set; }
        public int Stock_minimo { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Sucursales Sucursales { get; set; }
    }
}
