//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.Compras = new HashSet<Compras>();
        }
        [Required]
        [DisplayName("Código Proveedor:")]
        public string Cod_Prov { get; set; }
        [Required]
        [DisplayName("Empresa:")]
        public string Empresa { get; set; }
        [Required]
        [DisplayName("Nombre:")]
        public string Nombre_Prov { get; set; }
        [Required]
        [DisplayName("Apellido:")]
        public string Apellido_Prov { get; set; }
        [Required]
        [DisplayName("Teléfono:")]
        public int Telefono_Prov { get; set; }
        [Required]
        [DisplayName("Dirección:")]
        public string Direccion_Prov { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
    }
}
